# Generated by Django 5.0.4 on 2024-04-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_todo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='due_date',
        ),
    ]
