# Generated by Django 5.0.4 on 2024-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_todo_catigorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priorities',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
